#!/bin/bash
# User-specific aliases
alias vi="vim"
alias reload=". ~/.bash_profile"
alias ls="ls -1 --color=auto"
alias la="ls -a"
alias getnode="salloc --time=300:00:00 --ntasks=1 --cpus-per-task=12 --mem-per-cpu=10gb"
alias smallnode="salloc --time=05:00:00 --mem=10gb"
alias bignode="salloc --time=01:00:00 --mem=85gb"
alias proj="cd /project/noujdine_61/kdeweese"
alias long="cd /project/noujdine_61/kdeweese/latissima/longreads"
alias geno="cd /project/noujdine_61/kdeweese/latissima/genome_stats"
alias ass="cd /project/noujdine_61/kdeweese/latissima/organelles/org_assembly"
alias pop="cd /project/noujdine_61/kdeweese/latissima/organelles/org_pop_gen"
alias undar="cd /project/noujdine_61/mharden/undaria_variation"
